# Default values for ibp-parking-view.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor-state.space.com/ibp/parking
  pullPolicy: IfNotPresent
  tag: ""

####### 环境变量
FrontAddress:
  - name: iframeUrl
    value: http://spaas-sit.space.com
  - name: messageUrl
    value: http://spaas-sit.space.com
BackendApiUrl:
  - name: portalUrl
    value: http://portal-gateway-sit.space.com
  - name: baseUrl
    value: http://iot-gateway-web-sit.space.com
  - name: ibpUrl
    value: http://ibp-gateway-web-sit.space.com
  - name: messageWs
    value: http://message-channel-sit.space.com
  - name: uploadUrl
    value: http://iot-gateway-web-sit.space.com
  - name: vedioUrl
    value: http://iot-gateway-web-sit.space.com
  - name: spaceUrl
    value: http://portal-gateway-sit.space.com/space/v1
  - name: workOrderUrl
    value: http://spaas-sit.space.com
  - name: parkingUrl
    value: http://ibp-gateway-web-sit.space.com
  - name: spaasFlowUrl
    value: http://spaas-sit.space.com






ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: spaceiot-sit.space.com
      paths:
        - path: /parking
          pathType: ImplementationSpecific
  tls: []
